# -*- coding: utf-8 -*-
"""SimulatedDataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZeQf_NpasJu5ZFmA7I24MSdaRt3zBhv8
"""

import numpy as np
import pandas as pd
import os

def generar_dataset_simulado(n_pacientes=3000, n_biomarcadores=40, random_seed=42):
    # Fijamos la semilla para que sea 100% reproducible
    np.random.seed(random_seed)

    # 1. Nombrar las columnas
    columnas = [f'Biomarker_{i}' for i in range(n_biomarcadores)]
    columnas[0] = 'IL-6'  # Biomarcador Clave 1
    columnas[1] = 'IL-10' # Biomarcador Clave 2
    columnas[2] = 'TNF-a' # Biomarcador Cebo (Colineal)

    # 2. Generar distribuciones base simulando mediciones
    X = np.random.normal(loc=50, scale=15, size=(n_pacientes, n_biomarcadores))

    # 3. Forzar Colinealidad: TNF-a copia casi exactamente a IL-6
    X[:, 2] = X[:, 0] + np.random.normal(0, 2, n_pacientes)

    # 4. Establecer umbrales biológicos (Mediana)
    umbral_il6 = np.median(X[:, 0])
    umbral_il10 = np.median(X[:, 1])

    # 5. Inyectar la regla epistática estricta
    Y = np.zeros(n_pacientes, dtype=int)
    for i in range(n_pacientes):
        # LA REGLA OCULTA: SI (IL-6 es Alto) AND (IL-10 es Bajo) -> Infectado
        if X[i, 0] > umbral_il6 and X[i, 1] < umbral_il10:
            Y[i] = 1

    # 6. Empaquetar en DataFrame
    df = pd.DataFrame(X, columns=columnas)

    # 7. Introducir un 5% de ruido en el diagnóstico (voltear etiquetas)
    n_ruido = int(n_pacientes * 0.05)
    indices_ruido = np.random.choice(n_pacientes, size=n_ruido, replace=False)
    Y[indices_ruido] = 1 - Y[indices_ruido]

    # Añadir el Target al DataFrame y reordenar
    df['PathoCode'] = Y
    cols = ['PathoCode'] + columnas
    df = df[cols]

    return df

# ==========================================
# EJECUCIÓN DEL CÓDIGO
# ==========================================
print("Generando dataset simulado (Ground Truth)...")
df_simulado = generar_dataset_simulado(n_pacientes=3000, n_biomarcadores=40)

# Exportar a Excel
os.makedirs('data', exist_ok=True) # Crea la carpeta data si no existe
nombre_archivo = 'data/dataset_simulado_3000.xlsx'
df_simulado.to_excel(nombre_archivo, index=False)

print(f"¡Éxito! Dataset guardado en Colab como '{nombre_archivo}'.")